/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AudioPayer: typeof import('./src/components/videos/audio-payer.vue')['default']
    AudioPlayer: typeof import('./src/components/videos/audio-player.vue')['default']
    GenerateAudioDropdown: typeof import('./src/components/videos/generate-audio-dropdown.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    PreLoader: typeof import('./src/components/PreLoader.vue')['default']
    QuoteAudios: typeof import('./src/components/quote-audios.vue')['default']
    QuotesEditor: typeof import('./src/components/quotes-editor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VideoAudio: typeof import('./src/components/videos/video-audio.vue')['default']
    VideoAudioCard: typeof import('./src/components/videos/video-audio-card.vue')['default']
    VideoQuoteAudio: typeof import('./src/components/videos/video-quote-audio.vue')['default']
    VideoQuoteAudioCard: typeof import('./src/components/videos/video-quote-audio-card.vue')['default']
    VideoQuoteAudios: typeof import('./src/components/videos/video-quote-audios.vue')['default']
    VideoQuoteCard: typeof import('./src/components/videos/video-quote-card.vue')['default']
    VideoQuotesEditor: typeof import('./src/components/videos/video-quotes-editor.vue')['default']
  }
}
