export enum PlayhtVoices {
  Jordan = 'jordan',
  Bryan = 'bryan',
  Charles = 'charles',
  Cooper = 'cooper',
  Dane = 'dane',
  Donovan = 'donovan',
  Hudson = 'hudson',
  Jarrett = 'jarrett',
  Julian = 'julian',
  Larry = 'larry',
  LarryNarrative = 'larry_vo_narrative',
  Rodrick = 'rodrick',
  William = 'william',
  WilliamTraining = 'william_vo_training',
  WilliamNarrative = 'william_vo_narrative',
  Daniel = 'daniel',
  Arthur = 'arthur',
  ArthurMeditation = 'arthur_vo_meditation',
  ArthurNarrative = 'arthur_vo_narrative',
  ArthurTraining = 'arthur_vo_training',
  Aubrey = 'aubrey',
  Alex = 'alex',
}
